import { DeliveryProject, ProjectHealthMetrics } from './types';
import { recommendTeamAllocation, generateSprintPlan, generateMilestones } from './planning';
import { autoGenerateDeliveryTasks, detectDeliveryRisks } from './automation';
import { logger } from '@/lib/logger';

/**
 * AI Handoff Engine.
 * Converts a CONTRACT_SIGNED / WON deal directly into an active project workspace.
 */
export function createProjectFromWonDeal(
  dealId: string,
  companyName: string,
  domain: string,
  contractValueInr: string = '₹35,00,000',
  scopeSummary: string = '2-Engineer React 19 & Node.js Squad Allocation',
  techStack: string[] = ['React 19', 'Next.js 16', 'TypeScript', 'Node.js', 'PostgreSQL']
): DeliveryProject {
  logger.info(`AI Handoff Engine: Automatically creating project workspace for '${companyName}' from deal '${dealId}'...`);

  const team = recommendTeamAllocation(techStack);
  const pm = team.find(t => t.role === 'PROJECT_MANAGER')?.name || 'Siddharth Rao';
  const architect = team.find(t => t.role === 'SOLUTIONS_ARCHITECT')?.name || 'Vikram Mehta';

  const sprints = generateSprintPlan(scopeSummary);
  const milestones = generateMilestones();
  const risks = detectDeliveryRisks();
  const tasks = autoGenerateDeliveryTasks();

  const health: ProjectHealthMetrics = {
    deliveryScore: 94,
    riskScore: 12,
    timelineHealth: 'ON_TRACK',
    budgetHealth: 'ON_BUDGET',
    completionPercent: 25,
    qualityScorePercent: 98,
  };

  const documents = [
    {
      id: `doc_1`,
      documentType: 'SOW' as const,
      title: `${companyName} Statement of Work (SOW)`,
      fileUrl: `https://tinyscript.com/docs/sow-${domain}.pdf`,
      attachedAt: new Date().toISOString(),
    },
    {
      id: `doc_2`,
      documentType: 'MSA' as const,
      title: `${companyName} Master Services Agreement (MSA)`,
      fileUrl: `https://tinyscript.com/docs/msa-${domain}.pdf`,
      attachedAt: new Date().toISOString(),
    },
    {
      id: `doc_3`,
      documentType: 'ARCHITECTURE' as const,
      title: `${companyName} Technical Architecture Blueprint`,
      fileUrl: `https://tinyscript.com/docs/arch-${domain}.pdf`,
      attachedAt: new Date().toISOString(),
    },
  ];

  return {
    id: `proj_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
    dealId,
    companyName,
    domain,
    contractValueInr,
    contractValueUsd: '$42,000',
    scopeSummary,
    techStack,
    repoUrl: `https://github.com/tinyscript-org/${domain.split('.')[0]}-app`,
    cloudInfra: 'AWS ECS (Fargate) + PostgreSQL RDS',
    projectManager: pm,
    technicalArchitect: architect,
    team,
    sprints,
    milestones,
    risks,
    tasks,
    documents,
    health,
    status: 'KICKOFF',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}
