'use server';

import { AuthService } from '@/lib/auth';
import { logger } from '@/lib/logger';
import { AppError } from '@/lib/errors';
import { RevenueDeal, RevenueStage, RevenueTelemetry } from './types';

import { db } from '@/lib/db';
import { SettingsService } from '@/lib/settings';
import type { DealStage, Prisma } from '@prisma/client';
import { dealScope } from '@/features/crm/service';

// The Revenue pipeline is a view over the CRM's Deal table, so a deal has one stage everywhere.
// Deals are read-only here; stage changes happen in the CRM.
const TO_REVENUE_STAGE: Record<DealStage, RevenueStage> = {
  LEAD: 'NEW_LEAD',
  CONTACTED: 'QUALIFIED',
  MEETING_SCHEDULED: 'DISCOVERY_CALL',
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  NEGOTIATION: 'NEGOTIATION',
  WON: 'WON',
  LOST: 'LOST',
};

const USD_TO_INR = 83;

const revenueInclude = {
  company: true,
  owner: { select: { name: true } },
  tasks: { orderBy: { dueDate: 'asc' } },
  meetings: { orderBy: { startTime: 'desc' } },
  proposals: { orderBy: { createdAt: 'desc' } },
  activities: { orderBy: { createdAt: 'desc' }, take: 50, include: { user: { select: { name: true } } } },
} satisfies Prisma.DealInclude;

type DealRow = Prisma.DealGetPayload<{ include: typeof revenueInclude }>;

const day = (d: Date) => d.toISOString().split('T')[0];

function toRevenueDeal(deal: DealRow): RevenueDeal {
  const stage = TO_REVENUE_STAGE[deal.stage];
  const usd = deal.value || 0;
  return {
    id: deal.id,
    companyId: deal.companyId,
    companyName: deal.company.name,
    domain: deal.company.domain || '',
    stage,
    dealValueInr: `₹${(usd * USD_TO_INR).toLocaleString('en-IN')}`,
    dealValueUsd: `$${usd.toLocaleString('en-US')}`,
    buyingScore: deal.probability,
    winProbability: {
      currentWinPercent: deal.probability,
      revenueProbabilityPercent: deal.probability,
      riskLevelPercent: 100 - deal.probability,
      competitionLevelPercent: 0,
      urgencyPercent: 0,
      stakeholderEngagementPercent: 0,
      expectedCloseDate: deal.expectedCloseDate ? day(deal.expectedCloseDate) : '',
      confidenceLevel: deal.probability >= 80 ? 'VERY_HIGH' : deal.probability >= 60 ? 'HIGH' : deal.probability >= 30 ? 'MEDIUM' : 'LOW',
    },
    assignedBde: deal.owner?.name || 'Unassigned',
    assignedArchitect: '',
    meetings: deal.meetings.map((m) => ({
      id: m.id,
      meetingType: 'DISCOVERY',
      date: day(m.startTime),
      attendees: m.attendees,
      notes: m.notes || '',
      outcome: m.notes || '',
      nextAction: deal.nextAction || '',
    })),
    proposals: deal.proposals.map((p) => ({
      id: p.id,
      version: p.version || p.title,
      status: p.stage === 'DRAFT' ? 'DRAFT' : p.stage === 'WON' ? 'APPROVED' : p.stage === 'LOST' ? 'REJECTED' : 'SENT',
      createdDate: day(p.createdAt),
      budgetInr: p.amount ? `₹${(p.amount * USD_TO_INR).toLocaleString('en-IN')}` : '₹0',
      budgetUsd: p.amount ? `$${p.amount.toLocaleString('en-US')}` : p.budget,
      scopeSummary: p.scope || '',
      timelineWeeks: 0,
    })),
    contracts: [],
    tasks: deal.tasks.map((t) => ({
      id: t.id,
      title: t.title,
      description: '',
      category: 'OUTREACH',
      assignedTo: t.assignedOwner,
      dueDate: day(t.dueDate),
      status: t.status === 'COMPLETED' ? 'COMPLETED' : 'PENDING',
      autoGeneratedByStage: stage,
    })),
    timeline: deal.activities.map((a) => ({
      id: a.id,
      eventType: a.type,
      title: a.title,
      description: a.details || '',
      timestamp: a.createdAt.toISOString(),
      performedBy: a.user?.name || 'System',
    })),
    createdAt: deal.createdAt.toISOString(),
    updatedAt: deal.updatedAt.toISOString(),
  };
}

/**
 * Fetch all enterprise deals across RevenueOS pipeline stages.
 */
export async function getRevenueDealsAction(): Promise<RevenueDeal[]> {
  try {
    const user = await AuthService.verifySession();
    const deals = await db.deal.findMany({ where: dealScope(user), include: revenueInclude, orderBy: { lastActivityAt: 'desc' }, take: 1000 });
    logger.info(`Fetching ${deals.length} RevenueOS Enterprise Deals...`);
    return deals.map(toRevenueDeal);
  } catch (err: unknown) {
    logger.error('Failed to fetch revenue deals', { error: String(err) });
    throw new AppError('Failed to fetch revenue deals.', 500);
  }
}

/**
 * Fetch RevenueOS Telemetry KPIs.
 */
export async function getRevenueTelemetryAction(): Promise<RevenueTelemetry> {
  try {
    const user = await AuthService.verifySession();
    const deals = await db.deal.findMany({ where: dealScope(user), select: { stage: true, value: true, probability: true, createdAt: true, closedAt: true, expectedCloseDate: true } });

    const open = deals.filter((d) => d.stage !== 'WON' && d.stage !== 'LOST');
    const won = deals.filter((d) => d.stage === 'WON');
    const inr = (usd: number) => Math.round(usd * USD_TO_INR);

    const pipelineUsd = open.reduce((sum, d) => sum + (d.value || 0), 0);
    const weightedUsd = open.reduce((sum, d) => sum + ((d.value || 0) * d.probability) / 100, 0);
    const wonUsd = won.reduce((sum, d) => sum + (d.value || 0), 0);
    const valued = deals.filter((d) => d.value);
    const avgUsd = valued.length ? valued.reduce((sum, d) => sum + (d.value || 0), 0) / valued.length : 0;

    const now = new Date();
    const closingThisMonth = open.filter((d) => d.expectedCloseDate && d.expectedCloseDate.getFullYear() === now.getFullYear() && d.expectedCloseDate.getMonth() === now.getMonth()).length;
    const cycles = won.filter((d) => d.closedAt).map((d) => (d.closedAt!.getTime() - d.createdAt.getTime()) / 86400000);
    // The yearly target is set by an admin in Settings > Outreach; without one there is no progress to show.
    const annualTargetInr = Number(await SettingsService.get('annualSalesTargetInr', '').catch(() => '')) || 0;

    return {
      pipelineValueInr: `₹${inr(pipelineUsd).toLocaleString('en-IN')}`,
      pipelineValueUsd: `$${Math.round(pipelineUsd).toLocaleString('en-US')}`,
      expectedRevenueInr: `₹${inr(weightedUsd).toLocaleString('en-IN')}`,
      expectedRevenueUsd: `$${Math.round(weightedUsd).toLocaleString('en-US')}`,
      dealsClosingThisMonthCount: closingThisMonth,
      dealsWonCount: won.length,
      dealsLostCount: deals.filter((d) => d.stage === 'LOST').length,
      averageDealSizeInr: `₹${inr(avgUsd).toLocaleString('en-IN')}`,
      salesVelocityDays: cycles.length ? Math.round(cycles.reduce((a, b) => a + b, 0) / cycles.length) : 0,
      forecastAccuracyPercent: 0,
      annualSalesTargetInr: annualTargetInr ? `₹${annualTargetInr.toLocaleString('en-IN')}` : '',
      targetAchievementPercent: annualTargetInr ? Math.min(100, Number(((inr(wonUsd) / annualTargetInr) * 100).toFixed(1))) : 0,
    };
  } catch (err: unknown) {
    logger.error('Failed to query revenue telemetry', { error: String(err) });
    throw new AppError('Telemetry query failed.', 500);
  }
}
