'use server';

import { AuthService } from '@/lib/auth';
import { logger } from '@/lib/logger';
import { AppError } from '@/lib/errors';
import { safeRevalidatePath } from '@/lib/revalidate';
import { RevenueDeal, RevenueStage, RevenueTelemetry } from './types';
import { updateDealStage } from './pipeline';
import { autoGenerateStageTasks } from './automation';

import { db } from '@/lib/db';
import { PostStatus } from '@prisma/client';

const dealStore: Map<string, RevenueDeal> = new Map();

function initializeMockDeals() {
  if (dealStore.size > 0) return;

  const todayStr = new Date().toISOString().split('T')[0];

  const mock1: RevenueDeal = {
    id: 'deal-saaslabs',
    companyId: 'comp-saaslabs',
    companyName: 'SaaS Labs',
    domain: 'saaslabs.com',
    stage: 'PROPOSAL_SENT',
    dealValueInr: '₹35,00,000',
    dealValueUsd: '$42,000',
    buyingScore: 98,
    winProbability: {
      currentWinPercent: 75,
      revenueProbabilityPercent: 75,
      riskLevelPercent: 15,
      competitionLevelPercent: 20,
      urgencyPercent: 90,
      stakeholderEngagementPercent: 85,
      expectedCloseDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confidenceLevel: 'HIGH',
    },
    assignedBde: 'Akash (Lead BDE)',
    assignedArchitect: 'Solutions Architect',
    meetings: [
      {
        id: 'meet-1',
        meetingType: 'ARCHITECTURE',
        date: todayStr,
        attendees: ['nikitabhabani@saaslabs.com', 'akash@tiny-script.com'],
        notes: 'Google Meet: Technical Architecture & Squad Blueprint Review',
        outcome: 'Positive interest in Senior React 19 + Python FastAPI squad.',
        recordingUrl: 'https://meet.google.com/new',
        nextAction: 'Review commercial proposal and schedule MSA sign-off.'
      }
    ],
    proposals: [
      {
        id: 'prop-1',
        version: 'v1.0',
        status: 'SENT',
        createdDate: todayStr,
        budgetInr: '₹35,00,000',
        budgetUsd: '$42,000',
        scopeSummary: 'Dedicated Engineering Squad Acceleration (2-React 19 + Node.js devs)',
        timelineWeeks: 12
      }
    ],
    contracts: [],
    tasks: [
      {
        id: 'task-1',
        title: 'Follow-up on Commercial Proposal with Nikita Bhabani (CTO)',
        description: 'Send proposal review reminder and confirm Google Meet walkthrough.',
        category: 'MEETING',
        assignedTo: 'Lead BDE',
        dueDate: todayStr,
        status: 'PENDING',
        autoGeneratedByStage: 'PROPOSAL_SENT'
      }
    ],
    timeline: [
      {
        id: 'event-1',
        eventType: 'MEETING',
        title: 'Google Meet Scheduled: Technical Architecture Walkthrough',
        description: 'Scheduled with Nikita Bhabani (Chief Technology Officer)',
        timestamp: new Date().toISOString(),
        performedBy: 'Lead BDE'
      },
      {
        id: 'event-2',
        eventType: 'PROPOSAL_SENT',
        title: 'AI Commercial Proposal Generated & Sent',
        description: 'Sent proposal ₹35,00,000 for 2-Senior React 19 + Node.js Squad',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        performedBy: 'AI Proposal Generator'
      }
    ],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  };

  const mock2: RevenueDeal = {
    id: 'deal-vercel',
    companyId: 'comp-vercel',
    companyName: 'Vercel',
    domain: 'vercel.com',
    stage: 'CONTRACT_SENT',
    dealValueInr: '₹50,00,000',
    dealValueUsd: '$60,000',
    buyingScore: 96,
    winProbability: {
      currentWinPercent: 90,
      revenueProbabilityPercent: 90,
      riskLevelPercent: 10,
      competitionLevelPercent: 15,
      urgencyPercent: 95,
      stakeholderEngagementPercent: 90,
      expectedCloseDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      confidenceLevel: 'VERY_HIGH',
    },
    assignedBde: 'Akash (Lead BDE)',
    assignedArchitect: 'Solutions Architect',
    meetings: [
      {
        id: 'meet-2',
        meetingType: 'SALES',
        date: todayStr,
        attendees: ['guillermo@vercel.com', 'akash@tiny-script.com'],
        notes: 'Zoom: Executive MSA Contract Execution Sign-off',
        outcome: 'Legal terms agreed.',
        recordingUrl: 'https://zoom.us/j/bdos-vercel-contract',
        nextAction: 'Obtain electronic signature on MSA.'
      }
    ],
    proposals: [
      {
        id: 'prop-2',
        version: 'v1.0',
        status: 'APPROVED',
        createdDate: todayStr,
        budgetInr: '₹50,00,000',
        budgetUsd: '$60,000',
        scopeSummary: 'Enterprise Frontend Acceleration Squad',
        timelineWeeks: 16
      }
    ],
    contracts: [
      {
        id: 'contract-1',
        contractType: 'MSA',
        status: 'SENT',
        fileUrl: '#',
        executionDate: todayStr
      }
    ],
    tasks: [
      {
        id: 'task-2',
        title: 'Verify MSA Legal Signature Status for Vercel',
        description: 'Check legal team signature status for Master Services Agreement.',
        category: 'CONTRACT',
        assignedTo: 'Lead BDE',
        dueDate: todayStr,
        status: 'PENDING',
        autoGeneratedByStage: 'CONTRACT_SENT'
      }
    ],
    timeline: [
      {
        id: 'event-3',
        eventType: 'CONTRACT_SENT',
        title: 'Master Services Agreement (MSA) Sent for Signature',
        description: 'MSA contract sent to Guillermo Rauch (CEO)',
        timestamp: new Date().toISOString(),
        performedBy: 'Legal Contract Engine'
      }
    ],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date().toISOString(),
  };

  dealStore.set(mock1.id, mock1);
  dealStore.set(mock2.id, mock2);
}

/**
 * Fetch all enterprise deals across RevenueOS pipeline stages.
 */
export async function getRevenueDealsAction(): Promise<RevenueDeal[]> {
  try {
    await AuthService.verifySession();

    // Fetch real approved outreach posts from PostgreSQL Database (excluding DISMISSED)
    const dbPosts = await db.linkedInPost.findMany({
      where: {
        AND: [
          { status: { not: PostStatus.DISMISSED } },
          {
            OR: [
              { status: PostStatus.APPROVED },
              { status: PostStatus.REVIEW_QUEUE },
              { drafts: { some: {} } }
            ]
          }
        ]
      },
      include: {
        analysis: true,
        drafts: { orderBy: { generatedAt: 'desc' } }
      },
      orderBy: { discoveredAt: 'desc' }
    }).catch(() => []);

    const liveDeals: RevenueDeal[] = dbPosts
      .filter((post) => !dealStore.has(post.id))
      .map((post, idx) => {
      const draft = post.drafts[0];
      const isApproved = draft?.status === 'APPROVED' || post.status === 'APPROVED';

      let stage: RevenueStage = 'NEW_LEAD';
      if (isApproved) stage = 'QUALIFIED';

      let companyClean = post.companyName || 'Enterprise Lead';
      if (companyClean.toUpperCase() === 'ENTERPRISE.COM') {
        companyClean = 'Enterprise Lead';
      }

      let domainClean = companyClean.toLowerCase().replace(/[^a-z0-9]/g, '') + '.com';
      if (post.postUrl) {
        const parts = post.postUrl.split('/').filter(Boolean);
        const slug = parts[parts.length - 1] || '';
        if (slug && !slug.startsWith('urn:')) {
          domainClean = slug.replace(/\.com$/i, '') + '.com';
        }
      }

      return {
        id: post.id || `deal-${idx}`,
        companyId: `comp-${post.id || idx}`,
        companyName: companyClean,
        domain: domainClean,
        stage,
        dealValueInr: '₹50,00,000',
        dealValueUsd: '$60,000',
        buyingScore: post.opportunityScore || 90,
        winProbability: {
          currentWinPercent: isApproved ? 75 : 40,
          revenueProbabilityPercent: isApproved ? 75 : 40,
          riskLevelPercent: 20,
          competitionLevelPercent: 30,
          urgencyPercent: 80,
          stakeholderEngagementPercent: 70,
          expectedCloseDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
          confidenceLevel: 'HIGH',
        },
        assignedBde: 'Akash (Lead BDE)',
        assignedArchitect: 'Solutions Architect',
        meetings: [],
        proposals: [],
        contracts: [],
        tasks: [
          {
            id: `task-${post.id}-1`,
            title: `Stage 1 Initial Pitch for ${companyClean}`,
            description: `Initial pitch & discovery call for ${companyClean}`,
            category: 'OUTREACH',
            assignedTo: 'Lead BDE',
            dueDate: new Date().toISOString().split('T')[0],
            status: isApproved ? 'COMPLETED' : 'PENDING',
            autoGeneratedByStage: stage
          }
        ],
        timeline: [
          {
            id: `event-${post.id}-1`,
            eventType: 'DISCOVERY',
            title: `Lead Discovered: ${companyClean}`,
            description: `Signal score ${post.opportunityScore || 90}/100 matched on query '${post.matchedKeyword}'`,
            timestamp: post.discoveredAt ? new Date(post.discoveredAt).toISOString() : new Date().toISOString(),
            performedBy: 'AI Engine'
          }
        ],
        createdAt: post.discoveredAt ? new Date(post.discoveredAt).toISOString() : new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };
    });

    if (liveDeals.length === 0) {
      initializeMockDeals();
    }

    const memoryDeals = Array.from(dealStore.values());
    const allDeals = [...liveDeals, ...memoryDeals];

    logger.info(`Fetching ${allDeals.length} RevenueOS Enterprise Deals...`);
    return allDeals;
  } catch (err: unknown) {
    logger.error('Failed to fetch revenue deals', { error: String(err) });
    throw new AppError('Failed to fetch revenue deals.', 500);
  }
}

/**
 * Fetch RevenueOS Telemetry KPIs.
 */
export async function getRevenueTelemetryAction(): Promise<RevenueTelemetry> {
  try {
    await AuthService.verifySession();
    const deals = await getRevenueDealsAction();

    if (deals.length === 0) {
      return {
        pipelineValueInr: '₹0',
        pipelineValueUsd: '$0',
        expectedRevenueInr: '₹0',
        expectedRevenueUsd: '$0',
        dealsClosingThisMonthCount: 0,
        dealsWonCount: 0,
        dealsLostCount: 0,
        averageDealSizeInr: '₹0',
        salesVelocityDays: 0,
        forecastAccuracyPercent: 100,
        annualSalesTargetInr: '₹25,00,00,000',
        targetAchievementPercent: 0,
      };
    }

    let totalVal = 0;
    let weightedVal = 0;
    let wonCount = 0;
    let lostCount = 0;

    for (const d of deals) {
      const val = parseInt(d.dealValueInr.replace(/[^0-9]/g, ''), 10) || 5000000;
      const prob = d.winProbability?.currentWinPercent || 50;
      totalVal += val;
      weightedVal += (val * prob) / 100;
      if (d.stage === 'WON') wonCount++;
      if (d.stage === 'LOST') lostCount++;
    }

    const avg = deals.length > 0 ? Math.round(totalVal / deals.length) : 0;

    return {
      pipelineValueInr: `₹${totalVal.toLocaleString('en-IN')}`,
      pipelineValueUsd: `$${Math.round(totalVal / 83).toLocaleString('en-US')}`,
      expectedRevenueInr: `₹${Math.round(weightedVal).toLocaleString('en-IN')}`,
      expectedRevenueUsd: `$${Math.round(weightedVal / 83).toLocaleString('en-US')}`,
      dealsClosingThisMonthCount: deals.length,
      dealsWonCount: wonCount,
      dealsLostCount: lostCount,
      averageDealSizeInr: `₹${avg.toLocaleString('en-IN')}`,
      salesVelocityDays: 14,
      forecastAccuracyPercent: 96.4,
      annualSalesTargetInr: '₹25,00,00,000',
      targetAchievementPercent: Math.min(100, Number(((totalVal / 250000000) * 100).toFixed(1))),
    };
  } catch (err: unknown) {
    logger.error('Failed to query revenue telemetry', { error: String(err) });
    throw new AppError('Telemetry query failed.', 500);
  }
}

/**
 * Transition deal stage and auto-generate new stage tasks.
 */
export async function updateDealStageAction(dealId: string, newStage: RevenueStage): Promise<RevenueDeal> {
  try {
    await AuthService.verifySession();
    initializeMockDeals();
    let deal = dealStore.get(dealId);
    
    if (!deal) {
      const allDeals = await getRevenueDealsAction();
      deal = allDeals.find(d => d.id === dealId);
    }

    if (!deal) throw new AppError('Deal not found.', 404);

    const updated = updateDealStage(deal, newStage);
    const newTasks = autoGenerateStageTasks(newStage, deal.companyName);
    updated.tasks = [...newTasks, ...updated.tasks];
    dealStore.set(dealId, updated);

    safeRevalidatePath('/revenue');
    return updated;
  } catch (err: unknown) {
    logger.error(`Failed to update deal stage for '${dealId}'`, { error: String(err) });
    throw new AppError('Deal stage update failed.', 500);
  }
}

/**
 * Remove / Archive a deal from the RevenueOS Pipeline.
 */
export async function deleteRevenueDealAction(dealId: string): Promise<{ success: boolean }> {
  try {
    await AuthService.verifySession();
    logger.info(`Deleting revenue deal '${dealId}'...`);

    // Remove from in-memory store if present
    dealStore.delete(dealId);

    // Delete dependent records first to satisfy Prisma foreign key constraints
    await db.outreachDraft.deleteMany({ where: { postId: dealId } }).catch(() => null);
    await db.apolloEnrichment.deleteMany({ where: { linkedPostId: dealId } }).catch(() => null);
    await db.postAnalysis.deleteMany({ where: { postId: dealId } }).catch(() => null);

    // Delete parent post from PostgreSQL database
    try {
      await db.linkedInPost.delete({ where: { id: dealId } });
    } catch {
      // Fallback update status to DISMISSED if cascade delete is restricted
      await db.linkedInPost.updateMany({
        where: { id: dealId },
        data: { status: PostStatus.DISMISSED }
      }).catch(() => null);
    }

    safeRevalidatePath('/revenue');
    safeRevalidatePath('/review');
    safeRevalidatePath('/pipeline');
    return { success: true };
  } catch (err: unknown) {
    logger.error(`Failed to delete revenue deal '${dealId}'`, { error: String(err) });
    throw new AppError('Failed to delete deal.', 500);
  }
}
