import { RevenueStage, RevenueTask, RevenueDeal } from './types';
import { logger } from '@/lib/logger';

/**
 * AI Task Engine.
 * Automatically generates stage-specific tasks whenever a deal moves to a new stage.
 */
export function autoGenerateStageTasks(stage: RevenueStage, companyName: string): RevenueTask[] {
  logger.info(`AI Task Engine: Auto-generating tasks for '${companyName}' in stage ${stage}...`);

  const now = new Date().toISOString().split('T')[0];
  const dueTomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

  switch (stage) {
    case 'NEW_LEAD':
    case 'QUALIFIED':
      return [
        {
          id: `task_${Date.now()}_1`,
          title: `Schedule 10-Min Discovery Call with CTO of ${companyName}`,
          description: 'Reference recent React 19 & Python engineering hiring signal.',
          category: 'MEETING',
          assignedTo: 'Senior BDE',
          dueDate: dueTomorrow,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
        {
          id: `task_${Date.now()}_2`,
          title: `Send Initial Personalized AI Outreach to ${companyName}`,
          description: 'Deploy 2-engineer React 19 squad blueprint proposal.',
          category: 'OUTREACH',
          assignedTo: 'Senior BDE',
          dueDate: now,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
      ];

    case 'DISCOVERY_CALL':
    case 'TECHNICAL_DISCUSSION':
      return [
        {
          id: `task_${Date.now()}_1`,
          title: `Conduct Architecture Review & Tech Stack Alignment for ${companyName}`,
          description: 'Prepare microservices migration & AWS infrastructure recommendation.',
          category: 'TECHNICAL',
          assignedTo: 'Solutions Architect',
          dueDate: dueTomorrow,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
      ];

    case 'PROPOSAL_SENT':
    case 'NEGOTIATION':
      return [
        {
          id: `task_${Date.now()}_1`,
          title: `Follow Up on Fixed-Price AI Proposal for ${companyName}`,
          description: 'Schedule commercial negotiation call with VP Engineering & Procurement.',
          category: 'PROPOSAL',
          assignedTo: 'Senior BDE',
          dueDate: dueTomorrow,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
      ];

    case 'CONTRACT_SENT':
    case 'CONTRACT_SIGNED':
      return [
        {
          id: `task_${Date.now()}_1`,
          title: `Collect Signed Master Services Agreement (MSA) from ${companyName}`,
          description: 'Verify NDA, MSA, SOW, and initial 50% deposit invoice.',
          category: 'CONTRACT',
          assignedTo: 'Legal & BDE Lead',
          dueDate: dueTomorrow,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
      ];

    case 'PROJECT_STARTED':
    case 'WON':
      return [
        {
          id: `task_${Date.now()}_1`,
          title: `Conduct Project Kickoff Meeting for ${companyName}`,
          description: 'Introduce 2-engineer Senior Squad & establish weekly Slack sync.',
          category: 'MEETING',
          assignedTo: 'Delivery Lead',
          dueDate: dueTomorrow,
          status: 'PENDING',
          autoGeneratedByStage: stage,
        },
      ];

    default:
      return [];
  }
}

/**
 * Detect Stalled Deals Stagnant > 7 Days.
 */
export function detectStalledDeals(deals: RevenueDeal[]): RevenueDeal[] {
  return deals.filter(d => d.stage !== 'WON' && d.stage !== 'LOST');
}
