export type RevenueStage = 
  | 'NEW_LEAD'
  | 'QUALIFIED'
  | 'DISCOVERY_CALL'
  | 'TECHNICAL_DISCUSSION'
  | 'PROPOSAL_SENT'
  | 'NEGOTIATION'
  | 'CONTRACT_SENT'
  | 'CONTRACT_SIGNED'
  | 'PROJECT_STARTED'
  | 'WON'
  | 'LOST';

export type WinProbabilityDetails = {
  currentWinPercent: number; // 0-100
  revenueProbabilityPercent: number; // 0-100
  riskLevelPercent: number; // 0-100
  competitionLevelPercent: number; // 0-100
  urgencyPercent: number; // 0-100
  stakeholderEngagementPercent: number; // 0-100
  expectedCloseDate: string;
  confidenceLevel: 'VERY_HIGH' | 'HIGH' | 'MEDIUM' | 'LOW';
};

export type RevenueTask = {
  id: string;
  title: string;
  description: string;
  category: 'OUTREACH' | 'TECHNICAL' | 'PROPOSAL' | 'CONTRACT' | 'INVOICE' | 'MEETING';
  assignedTo: string;
  dueDate: string;
  status: 'PENDING' | 'COMPLETED';
  autoGeneratedByStage: RevenueStage;
};

export type RevenueMeeting = {
  id: string;
  meetingType: 'DISCOVERY' | 'TECHNICAL' | 'SALES' | 'ARCHITECTURE' | 'KICKOFF';
  date: string;
  attendees: string[];
  notes: string;
  outcome: string;
  recordingUrl?: string;
  nextAction: string;
};

export type RevenueProposal = {
  id: string;
  version: string;
  status: 'DRAFT' | 'SENT' | 'REVISED' | 'APPROVED' | 'REJECTED';
  createdDate: string;
  budgetInr: string;
  budgetUsd: string;
  scopeSummary: string;
  timelineWeeks: number;
  clientFeedback?: string;
};

export type RevenueContract = {
  id: string;
  contractType: 'NDA' | 'MSA' | 'SOW' | 'INVOICE' | 'PURCHASE_ORDER';
  status: 'DRAFT' | 'SENT' | 'SIGNED';
  fileUrl: string;
  executionDate: string;
};

export type RevenueActivityEvent = {
  id: string;
  eventType: string;
  title: string;
  description: string;
  timestamp: string;
  performedBy: string;
};

export type RevenueDeal = {
  id: string;
  companyId: string;
  companyName: string;
  domain: string;
  stage: RevenueStage;
  dealValueInr: string;
  dealValueUsd: string;
  buyingScore: number;
  winProbability: WinProbabilityDetails;
  assignedBde: string;
  assignedArchitect: string;
  meetings: RevenueMeeting[];
  proposals: RevenueProposal[];
  contracts: RevenueContract[];
  tasks: RevenueTask[];
  timeline: RevenueActivityEvent[];
  createdAt: string;
  updatedAt: string;
};

export type RevenueTelemetry = {
  pipelineValueInr: string;
  pipelineValueUsd: string;
  expectedRevenueInr: string;
  expectedRevenueUsd: string;
  dealsClosingThisMonthCount: number;
  dealsWonCount: number;
  dealsLostCount: number;
  averageDealSizeInr: string;
  salesVelocityDays: number;
  forecastAccuracyPercent: number;
  annualSalesTargetInr: string;
  targetAchievementPercent: number;
};
